# MATH&STAT-1. Линейная алгебра. Часть I 
## Юнит 3. Введение в машинное обучение 
### Skillfactory: DST-10
---
### 1.2. Векторы. Основные понятия

In [1]:
import numpy as np
s = np.array([33,65,50,45])
print(f"s:={s}")
print(f"len(s):={len(s)}")
print(f"третий элемент массива:= {s[2]}")

s:=[33 65 50 45]
len(s):=4
третий элемент массива:= 50


In [2]:
apartment = np.array([59.50, 31.40, 19, 2, 60550, 2])
# В NumPy вектор и массив - одно и то же. 
# Исключение - понятие вектор-столбец и вектор-строка - фактически двумерные массивы, 
# где один из атрибутов shape равен 1.

print("ndim:", apartment.ndim) # число осей (измерений) массива - n.dim: 1
print("shape:", apartment.shape) # размеры массива, для вектора определена только длина - shape: (6, )

ndim: 1
shape: (6,)


In [3]:
# вычислим долю жилой площади в квартире
share_living_space = apartment[1]/apartment[0]
print(share_living_space)

#Избавимся от старых признаков, посредством функции delete(), которую предоставляет библиотека numpy. Передадим в значение функции индексы признаков, которые необходимо удалить из нашего массива apartment:
apartment = np.delete(apartment, [0, 1])
print(apartment)

0.5277310924369748
[1.900e+01 2.000e+00 6.055e+04 2.000e+00]


In [4]:
# добавим в конец нашего массива новый признак share_living_space, который сочетает в себе смысл двух старых признаков:
apartment = np.append(apartment, share_living_space)
print(*apartment)
# !внимание! тут поставлена * перед массивом, чтобы вывести значения в обычном формате, а не е+01

19.0 2.0 60550.0 2.0 0.5277310924369748


### Задание 1.2.1
Введите значение получившегося нового признака share_living_space. Используйте код и ссылки на документацию из описания квартиры.

In [5]:
temp = apartment[4]

task = "1.2.1"
print(f"Ответ к заданию {task}")
print(f"значение получившегося нового признака share_living_space := {round(temp,2)}")

Ответ к заданию 1.2.1
значение получившегося нового признака share_living_space := 0.53


### Задание 1.2.2
Найдите размерность и четвёртую координату вектора

In [6]:
v = np.array([-1, 4, 6, 1, 8, 2])
n = 4
temp = v[n-1]

task = "1.2.2"
print(f"Ответ к заданию {task}")
print(f"размерность вектора v [-1, 4, 6, 1, 8, 2]:= {len(v)}")
print(f"четвёртую координату вектора v:= {temp}")

Ответ к заданию 1.2.2
размерность вектора v [-1, 4, 6, 1, 8, 2]:= 6
четвёртую координату вектора v:= 1


### Задание 1.2.2 (!!! обратите внимание!!! нумерация задачи 1.2.2 была задублирована)
Укажите размерность конечного массива apartment после преобразования (ввода новой переменной и удаления старых).

In [7]:
temp = len(apartment)

task = "1.2.2"
print(f"Ответ к заданию {task}")
print(f"размерность вектора apartment:= {temp}")

Ответ к заданию 1.2.2
размерность вектора apartment:= 5


### Задание 1.2.3
Пусть дан вектор в python вида t = np.array(\[12, 14, 17, 19, 24, 28, 31, 31, 27, 22, 17, 13\]), содержащий информацию о средней температуре воздуха (в градусах Цельсия) в Риме с января по декабрь включительно.
Выберите неверное утверждение:

### 1.3. Базовые операции над векторами
---
### Задание 1.3.2
Найдите сумму и разность вектров x=(\[5,2\]) и y=(\[-5,-11\])

In [9]:
x = np.array([5, 2])
y = np.array([-5, -11])
temp = x+y
temp2 = x-y

task = "1.3.2"
print(f"Ответ к заданию {task}")
print(f"x+y:= {temp}")
print(f"x-y:= {temp2}")

Ответ к заданию 1.3.2
x+y:= [ 0 -9]
x-y:= [10 13]


### Задание 1.3.3  
Доходы Алексея за три месяца составили 120, 150 и 90 тысяч рублей, его жены: 130, 130 и 130 тысяч рублей, а тёщи: 2, 3 и 2.5 тысячи евро.  
1. Найдите вектор доходов тёщи в тыс. рублей, если курс евро составляет 72 рубля.  
2. Найдите вектор суммарного дохода семьи в тыс. рублей по месяцам.

In [10]:
husband_RUR = np.array([120, 150, 90])
wife_RUR = np.array([130, 130, 130])
mother_in_law_EUR = np.array([2, 3, 2.5])

temp = mother_in_law_EUR*72
temp2 = temp+husband_RUR+wife_RUR

task = "1.3.3"
print(f"Ответ к заданию {task}")
print(f"вектор доходов тёщи в тыс. рублей:= {temp}")
print(f"вектор суммарного дохода семьи в тыс. рублей:= {temp2}")

Ответ к заданию 1.3.3
вектор доходов тёщи в тыс. рублей:= [144. 216. 180.]
вектор суммарного дохода семьи в тыс. рублей:= [394. 496. 400.]


### !!!офтопик!!!
### Инструкция по формулам в Markdown
---
$ L(x_{1}, x_{2}, ..., x_{n}  
 \mu) =  \mu * (1-\mu) $

$log (\ L(x_{1}, x_{2}, ..., x_{n}| \mu)) = h * log(\mu) + (m-h) * log(1-\mu) $

$\frac{\partial  log(\ L(x_{1}, x_{2}, ..., x_{n}| \mu)}{\partial(\mu)}  = \frac{h}{\  u} + \frac{h-m}{1-\mu} $

#### We set this to zero to find the value that  aximizes the likelihood 

$\frac{h}{\mu}    \frac{h-m}{1-\  u} = 0 $

$h = m * \mu $

$\mu = \frac{h}{m} $

### 1.4. Линейная комбинация векторов
---
### Задание 1.4.1
Найдите линейную комбинацию векторов  
$x = {4 \choose 5} , y = {2 \choose 1}, u = {0 \choose 1}$  
с коэффициентами 2, -3, 5

In [12]:
x = np.array([4,5])
y = np.array([2,1])
u = np.array([1,0])
a, b, c = 2, -3, 5

temp = a*x + b*y + c*u

task = "1.4.1"
print(f"Ответ к заданию {task}")
print(f"линейную комбинацию векторов:= {temp}")

Ответ к заданию 1.4.1
линейную комбинацию векторов:= [7 7]


### Задание 1.4.2  
Юный предприниматель Вовочка мастерит ракеты на водном топливе и продает их. За 4 недели он смастерил 3, 4, 5 и 9 ракет, а продал 1, 5, 3 и 6 ракет соответственно.  
На изготовление одной ракеты он тратит 200 рублей, а продаёт их по 400 рублей за штуку.  
Найдите вектор прибыли Вовочки за эти 4 недели.

In [13]:
weeklyRocketProduction = np.array([3,4,5,9])
weeklyRocketSales = np.array([1,5,3,6])
unitProductionСosts = 200
unitSalesPrice = 400
unitMargin = unitSalesPrice - unitProductionСosts

temp = unitSalesPrice*weeklyRocketSales - unitProductionСosts*weeklyRocketProduction

task = "1.4.2"
print(f"Ответ к заданию {task}")
print(f"вектор прибыли Вовочки за эти 4 недели:= {temp}")

Ответ к заданию 1.4.2
вектор прибыли Вовочки за эти 4 недели:= [-200 1200  200  600]


### Задание 1.4.3
Какие системы векторов являются линейно зависимыми?  
***Ответ:***  
$x = {-1 \choose -2} , y = {1 \choose 2}$    
$x = {-3 \choose -2} , y = {1 \choose 1}, u = {4 \choose 3}$  

### 1.5. Скалярное произведение векторов
---
Задание 1.5.1
Результатом скалярного произведения векторов является  

***Ответ:*** Число  

### Задание 1.5.2
Найдите скалярное произведение векторов  
```python
x = np.array([4,5,-1])
y = np.array([2,0,1])
```

In [14]:
x = np.array([4,5,-1])
y = np.array([2,0,1])

temp = np.dot(x,y)

task = "1.5.2"
print(f"Ответ к заданию {task}")
print(f"скалярное произведение векторов:= {temp}")

Ответ к заданию 1.5.2
скалярное произведение векторов:= 7


### Задание 1.5.3
Выберите верные утверждения о длине вектора  
***Ответ:*** 
- Длина вектора равна нулю, только если сам вектор нулевой  
- Квадрат длины вектора равен его скалярному произведению с самим собой  
---
### Задание 1.5.4
Вычислите длину вектора ```x = np.array([4,6,1])```. Ответ округлите до сотых.

In [15]:
x = np.array([4,6,1])

temp = np.dot(x,x)**0.5

task = "1.5.4"
print(f"Ответ к заданию {task}")
print(f"длину вектора x:= {round(temp,2)}")

Ответ к заданию 1.5.3
длину вектора x:= 7.28


### 1.6. Векторы. Практическая задача
---
### Задание 1.6.1
Прогноз оптимальной арендной платы для новой квартиры не изменился после добавления информации о нежилой площади, так как:  
***Ответ:*** Новый фактор линейно зависим со старыми

### Задание 1.6.2
Комментарий к заданию 1.6.2. Длина вектора - число, которое ставится в соответствие каждому элементу векторного пространства. Оно у разных векторов может совпадать или различаться. При этом векторы имеют равное количество координат, потому что они из одного пространства определенной размерности. И операция сложения, заданная на пространстве, предполагает, что слагаемые имеют равное количество координат. Но они могут иметь как одну длину, так и различную.  
Выберите верные утверждения:  
***Ответ:***  
- Угол между ортогональными векторами составляет 90 градусов
- если a||b и b||c, то a||c

### 1.7. --> Практика. Векторы

In [16]:
# как одномерный массив numpy
a=np.array([1,2,3])
print(a, type(a))

[1 2 3] <class 'numpy.ndarray'>


In [17]:
np.array([1,2,3], dtype='float')

array([1., 2., 3.])

In [18]:
# преобразовать из списка (list)
x=[1,2,3]
x_arr=np.array(x)
print(x, type(x))
print(x_arr, type(x_arr))

[1, 2, 3] <class 'list'>
[1 2 3] <class 'numpy.ndarray'>


In [19]:
# нулевой вектор
np.zeros(5) 

array([0., 0., 0., 0., 0.])

In [20]:
# вектор из единиц
np.ones(8)

array([1., 1., 1., 1., 1., 1., 1., 1.])

In [21]:
# массив чисел по порядку
np.arange(10,50, 5)

array([10, 15, 20, 25, 30, 35, 40, 45])

In [22]:
# случайный вектор
np.random.randint(-4, 2, 10) # dim=10, случаные целые числа от -4 до 2

array([-1, -2, -4, -3, -4, -4,  0, -1, -2,  1])

In [23]:
# преобразовать из Pandas Series
import pandas as pd
data = [65, 70, 120, 35]
s = pd.Series(data)
print('Series:\n',s)

Series:
 0     65
1     70
2    120
3     35
dtype: int64


In [24]:
x = s.values # возвращает значения s
print('vector:\n',x)
print('type of x:',type(x))

vector:
 [ 65  70 120  35]
type of x: <class 'numpy.ndarray'>


In [25]:
# преобразовать из Pandas DataFrame
d = {'$$': [65, 70, 120, 35], '2.Area': [50, 52, 80, 33],'3.Rooms':[3,2,1,1], 
     '4.Floor':[5,12,10,3], '5.Demo':[8,4,5,10]}
df = pd.DataFrame(d)
print('Data Frame:\n',df)

Data Frame:
     $$  2.Area  3.Rooms  4.Floor  5.Demo
0   65      50        3        5       8
1   70      52        2       12       4
2  120      80        1       10       5
3   35      33        1        3      10


In [26]:
A = df.values # возвращает значения df
print('Matrix:\n',A)

Matrix:
 [[ 65  50   3   5   8]
 [ 70  52   2  12   4]
 [120  80   1  10   5]
 [ 35  33   1   3  10]]


In [27]:
x=A[1] # вторая строка матрицы А
print('Second apartment vector:\n',x)
print('type of x:',type(x))

Second apartment vector:
 [70 52  2 12  4]
type of x: <class 'numpy.ndarray'>


In [28]:
y=A[:,0] # первый столбец матрицы А
print('$$ vector:\n',y)

$$ vector:
 [ 65  70 120  35]


In [29]:
# индексация векторов - поиск нужной координаты
print('$$ of 3 apartment:',y[2]) # третья координата

$$ of 3 apartment: 120


In [30]:
# размерность вектора
print('Number of apartments = dim(y):', len(y))

Number of apartments = dim(y): 4


In [31]:
# сумма векторов и умножение на число
a=np.array([1,2,3])
b=np.array([6,7,8])
print('a+b:',a+b)
print('2a:',2*a)

a+b: [ 7  9 11]
2a: [2 4 6]


In [32]:
# линейная комбинация с коэффициентами 2, 2, 3
a=np.array([1,2,3])
b=np.array([6,7,8])
c=np.array([1,0,1])

d=2*a+2*b+3*c
print('linear combination:',d)

linear combination: [17 18 25]


In [33]:
# скалярное произведение

s=np.dot(a,b)
print('scalar product:',s)

# покоординатное умножение
print('coordinate product:',a*b)

scalar product: 44
coordinate product: [ 6 14 24]


In [34]:
# скалярное произведение - еще один способ
s1=a@b
print('scalar product:',s1)

scalar product: 44


In [35]:
# длина вектора
l=np.linalg.norm(a)
print('length of a:',l)

length of a: 3.7416573867739413


In [36]:
# нормировка
a_norm=a/np.linalg.norm(a)
print('a_norm:',a_norm)
print('length of a_norm:',np.linalg.norm(a_norm))

a_norm: [0.26726124 0.53452248 0.80178373]
length of a_norm: 1.0


In [37]:
#пропорциональность и ортогональность
a=np.array([1,2,1])
b=a*2
c=np.array([-1,1,-1])
print('a:',a)
print('b:',b)
print('c:',c)

a: [1 2 1]
b: [2 4 2]
c: [-1  1 -1]


In [38]:
#пропорциональность и ортогональность
print("(a,b):",np.dot(a,b))
print("(a,c):",np.dot(a,c))
print("(b,c):",np.dot(b,c))

(a,b): 12
(a,c): 0
(b,c): 0


In [39]:
# попарная ортогональность - да
a=np.array([1,0,1])
b=np.array([0,1,0])
c=np.array([1,0,-1])
print('a:',a)
print('b:',b)
print('c:',c)

a: [1 0 1]
b: [0 1 0]
c: [ 1  0 -1]


In [40]:
# попарная ортогональность - да
print('(a,b):',np.dot(a,b))
print('(b,c):',np.dot(b,c))
print('(a,c):',np.dot(a,c))

(a,b): 0
(b,c): 0
(a,c): 0


In [41]:
# попарная ортогональность - нет
c1=np.array([1,0,4])
print('a:',a)
print('b:',b)
print('с1:',c1)

a: [1 0 1]
b: [0 1 0]
с1: [1 0 4]


In [42]:
# попарная ортогональность - нет
print('(a,b):',a@b)
print('(b,c1):',b@c1)
print('(a,c1):',a@c1)

(a,b): 0
(b,c1): 0
(a,c1): 5


### Задача 1.7.1. 
Условие
В Hut_Paradise_DF представлен фрагмент базы данных агенства «Рай в Шалаше». По строкам расположены квартиры, по столбцам — параметры: арендная плата, общая площадь, количество комнат, этаж, количество показов на две недели и жилая площадь:

In [43]:
Hut_Paradise_DF = pd.DataFrame({'1.Rent': [65, 70, 120, 35, 40, 50, 100, 90, 85], 
                                '2.Area': [50, 52, 80, 33, 33, 44, 80, 65, 65], 
                                '3.Rooms':[3, 2, 1, 1, 1, 2, 4, 3, 2],
                                '4.Floor':[5, 12, 10, 3, 6, 13, 8, 21, 5], 
                                '5.Demo two weeks':[8, 4, 5, 10, 20, 12, 5, 1, 10], 
                                '6.Liv.Area': [37, 40, 65, 20, 16, 35, 60, 50, 40]})

### Задание 1.7.1
Найдите вектор параметров квартиры номер 5

In [44]:
df = pd.DataFrame(Hut_Paradise_DF)
print('Data Frame:\n',df)

Data Frame:
    1.Rent  2.Area  3.Rooms  4.Floor  5.Demo two weeks  6.Liv.Area
0      65      50        3        5                 8          37
1      70      52        2       12                 4          40
2     120      80        1       10                 5          65
3      35      33        1        3                10          20
4      40      33        1        6                20          16
5      50      44        2       13                12          35
6     100      80        4        8                 5          60
7      90      65        3       21                 1          50
8      85      65        2        5                10          40


In [45]:
A = df.values # возвращает значения df
print('Matrix:\n',A)

Matrix:
 [[ 65  50   3   5   8  37]
 [ 70  52   2  12   4  40]
 [120  80   1  10   5  65]
 [ 35  33   1   3  10  20]
 [ 40  33   1   6  20  16]
 [ 50  44   2  13  12  35]
 [100  80   4   8   5  60]
 [ 90  65   3  21   1  50]
 [ 85  65   2   5  10  40]]


In [46]:
temp = x=A[4] # пятая строка матрицы А

task = "1.7.1"
print(f"Ответ к заданию {task}")
print(f"вектор параметров квартиры номер 5:= {temp}")

Ответ к заданию 1.7.1
вектор параметров квартиры номер 5:= [40 33  1  6 20 16]


### Задание 1.7.2
Найдите вектор этажей всех квартир:

In [47]:
temp = y=A[:,3] # четвертый столбец матрицы А

task = "1.7.2"
print(f"Ответ к заданию {task}")
print(f"вектор этажей всех квартир:= ", end="")
print(*temp, sep=",")

Ответ к заданию 1.7.2
вектор этажей всех квартир:= 5,12,10,3,6,13,8,21,5


### Задание 1.7.3
На каком этаже расположена квартира номер 3?

In [48]:
temp = y[2]

task = '1.7.3'
print(f"Ответ к заданию {task}")
print(f"квартира номер 3 расположена на:= {temp} этаже")

Ответ к заданию 1.7.3
квартира номер 3 расположена на:= 10 этаже


### Задание 1.7.4
Найдите количество квартир

In [49]:
temp = len(A)

task = '1.7.4'
print(f"Ответ к заданию {task}")
print(f"количество квартир:= {temp}")

Ответ к заданию 1.7.4
количество квартир:= 9


### Задание 1.7.5  
Вычислите вектор нежилой площади:

In [50]:
y2 = A[:,1] # второй столбец матрицы А - Area
y6 = A[:,5] # шестой столбец матрицы А - Liv.Area
temp = y2-y6

task = '1.7.5'
print(f"Ответ к заданию {task}")
print(f"вектор нежилой площади:= ", end="")
print(*temp, sep=",")

Ответ к заданию 1.7.5
вектор нежилой площади:= 13,12,15,13,17,9,20,15,25


### Задание 1.7.6
Арендная плата измеряется в тысячах рублей. Пересчитайте стоимость аренды каждой квартиры в тысячах гривен, если курс 10 руб = 4 гривны

In [51]:
y1 = A[:,0] # первый столбец матрицы А - Rent

temp = np.array(y1/2.5, dtype='int')

task = '1.7.6'
print(f"Ответ к заданию {task}")
print(f"стоимость аренды каждой квартиры в тысячах гривен:= ", end="")
print(*temp, sep=",")

Ответ к заданию 1.7.6
стоимость аренды каждой квартиры в тысячах гривен:= 26,28,48,14,16,20,40,36,34


### Задание 1.7.7
Пусть в первой квартире один просмотр занимает 10 минут, во второй — 20 минут, в третьей — полчаса, в четверой — 15 минут, в пятой — 5 минут, в шестой — 40 минут, в седьмой — 20 минут, в восьмой — 8 минут и в девятой — 20 минут. Найдите продолжительность просмотров в минутах во всех квартирах за 2 недели:

In [52]:
x = np.array([10,20,30,15,5,40,20,8,20])
y1 = A[:,4] # пятый столбец матрицы А - Demo two weeks

temp = np.dot(y1,x)  # скалярное произведение

task = '1.7.7'
print(f"Ответ к заданию {task}")
print(f"продолжительность просмотров в минутах во всех квартирах за 2 недели:= {temp}")

Ответ к заданию 1.7.7
продолжительность просмотров в минутах во всех квартирах за 2 недели:= 1348


### Задача 2. 
***Условие:***
Даны три вектора:  
u=np.array(\[3,0,1,1,1\])  
v=np.array(\[0,1,0,2,-2\])  
w=np.array(\[1,-4,-1,0,-2\])  
Проверьте, являются ли векторы попарно ортогональными.  

### Задание 1.7.8  
Составьте линейную комбинацию векторов v и w с коэффициентами 2 и -3:

In [53]:
u=np.array([3,0,1,1,1])
v=np.array([0,1,0,2,-2])
w=np.array([1,-4,-1,0,-2])
a, b = 2, -3

temp= 2*v - 3*w

task = '1.7.8'
print(f"Ответ к заданию {task}")
print(f"линейная комбинация векторов v и w с коэффициентами 2 и -3 := ", end="")
print(*temp, sep=",")

Ответ к заданию 1.7.8
линейная комбинация векторов v и w с коэффициентами 2 и -3 := -3,14,3,4,2


### Задание 1.7.9
Будет ли эта комбинация ортогональна вектору u?

In [54]:
temp =np.dot(u,temp)  # скалярное произведение

task = '1.7.9'
print(f"Ответ к заданию {task}")
print(f"скалярное произведение u и  x равно"
      f":= {temp}")
print("Ответ - да ")

Ответ к заданию 1.7.9
скалярное произведение u и  x равно:= 0
Ответ - да 


### Задание 1.7.10
Нормируйте векторы u,v,w. 
В ответ запишите, округлив до трёх знаков после точки:  
1. третью координату u_norm   
2. четвертую координату v_norm  
3. первую координату w_norm

In [55]:
temp1 = (u/np.linalg.norm(u))[2]
temp2 = (v/np.linalg.norm(v))[3]
temp3 = (w/np.linalg.norm(w))[0]

task = '1.7.10'
print(f"Ответ к заданию {task}")
print(f"1. третья координата u_norm"
      f":= {round(temp1,3)}")
print(f"2. четвертую координату v_norm"
      f":= {round(temp2,3)}")
print(f"3. первую координату w_norm"
      f":= {round(temp3,3)}")

Ответ к заданию 1.7.10
1. третья координата u_norm:= 0.289
2. четвертую координату v_norm:= 0.667
3. первую координату w_norm:= 0.213


### 1.8. Матрицы. Основные понятия

In [56]:
A = np.array([[1,-5,3],[2,2,1],[0,3,1],[2,4,12]])
print(f'Матрица А:')
print(A)
print(f'A.shape:= {A.shape}')
print(f'A[1,2]:= {A[1,2]}')
print(f'A[2,1]:= {A[2,1]}')
print(f'A[2,2]:= {A[2,2]}')
B = np.matrix([[1,0,0],[0,1,0],[0,0,1]])
B

Матрица А:
[[ 1 -5  3]
 [ 2  2  1]
 [ 0  3  1]
 [ 2  4 12]]
A.shape:= (4, 3)
A[1,2]:= 1
A[2,1]:= 3
A[2,2]:= 1


matrix([[1, 0, 0],
        [0, 1, 0],
        [0, 0, 1]])

### 1.9. Базовые действия над матрицами

In [57]:
C = np.matrix([[1,1,0],[0,1,1],[1,1,0]])
D = B+C
print(f"матрица D")
print(D)
print()
print(f"матрица D.T")
print(D.T)

матрица D
[[2 1 0]
 [0 2 1]
 [1 1 1]]

матрица D.T
[[2 0 1]
 [1 2 1]
 [0 1 1]]


### 1.10. --> Практика. Базовые действия над матрицами

In [73]:
# как создать матрицу?
# как двумерный массив Numpy
np.array( [ [1,1] , [2,3] , [4,5] ] )

# преобразовать из Pandas DataFrame
data=[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]
df = pd.DataFrame(data)

A = df.values
print('Data Frame:')
print(df)
print('Matrix:')
print(A)

SyntaxError: invalid syntax (<ipython-input-73-0b385a5488bf>, line 3)

In [59]:
# размер матрицы
np.shape(A)

(4, 3)

In [60]:
# вектор-столбец
x=np.array([1,2,3])
np.reshape(x,(3,1))

array([[1],
       [2],
       [3]])

In [61]:
# вектор-строка
np.reshape(x,(1,3))

array([[1, 2, 3]])

In [62]:
# вектор-строка
x_row=np.array([1, 2, 3], ndmin=2)
print(x_row,np.shape(x_row))

[[1 2 3]] (1, 3)


In [63]:
# индексация матриц (двумерных массивов numpy)
print('матрица А:')
print(A)
print('Первая строка матрицы А:')
print(A[0])
print('Третий столбец матрицы А:')
print(A[:,2])
print('Элемент а_43:')
print(A[3,2])

матрица А:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Первая строка матрицы А:
[1 2 3]
Третий столбец матрицы А:
[ 3  6  9 12]
Элемент а_43:
12


In [64]:
# создание специальных матриц

# нулевая
print(np.zeros((2,3)))
print()

# единичная
print(np.eye(3))

# матрица единиц
np.ones((3,5))

[[0. 0. 0.]
 [0. 0. 0.]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [65]:
# Диагональная
diagonal=[1,2,3]
print(np.diag(diagonal))
print()

# Шаровая
5*np.eye(3)

[[1 0 0]
 [0 2 0]
 [0 0 3]]



array([[5., 0., 0.],
       [0., 5., 0.],
       [0., 0., 5.]])

In [66]:
A=np.array([[1,1],[2,3],[4,5]])
B=np.array([[1,-1],[-2,3],[4,-5]])

print(A)
print()

print(B)
print()

print(A+B)
print()

print(B+A)
print()

print(A-B)
print()

print(2*A)
print()

print(A.T)
print()

[[1 1]
 [2 3]
 [4 5]]

[[ 1 -1]
 [-2  3]
 [ 4 -5]]

[[2 0]
 [0 6]
 [8 0]]

[[2 0]
 [0 6]
 [8 0]]

[[ 0  2]
 [ 4  0]
 [ 0 10]]

[[ 2  2]
 [ 4  6]
 [ 8 10]]

[[1 2 4]
 [1 3 5]]



In [67]:
# как транспонировать вектор?
x=np.array([1,2,3])
print(x.T)
print()

x_col=np.reshape(x,(3,1))
print(x_col)
print(np.shape(x_col))
print()

print(x_col.T)

print(np.shape(x))
print()

print(np.shape(x_col))
print()

print(np.shape(x_col.T))
print()

[1 2 3]

[[1]
 [2]
 [3]]
(3, 1)

[[1 2 3]]
(3,)

(3, 1)

(1, 3)



### Задача 1.10.1 
***Условие:*** Данные по доходам и расходам каждого члена семьи Ивановых записаны в одномерные массивы NumPy

In [68]:
Husband_Income=np.array([100,220,140])
Wife_Income=np.array([150,200,130])
Lover_Income=np.array([90,80,100])

Husband_Сonsumption=np.array([50,50,60])
Wife_Сonsumption=np.array([100,80,140])
Lover_Сonsumption=np.array([100,20,140])

### Задание 1.10.1
Составьте матрицу Inc доходов семьи, расположив доходы мужа, жены и любовницы в первый, второй и третий столбцы:  
В ответ запишите диагональные элементы (по главной диагонали) этой матрицы через запятую (без пробела):

In [69]:
A = np.array([ Husband_Income , Wife_Income , Lover_Income ])
Inc = A.T
temp  = np.diagonal(Inc)

task = '1.10.1'
print(f"Ответ к заданию {task}")
print(f"диагональные элементы (по главной диагонали) матрицы Inc:= ", end="")
print(*temp, sep=",")

Ответ к заданию 1.10.1
диагональные элементы (по главной диагонали) матрицы Inc:= 100,200,100


### Задание 1.10.2
Составьте матрицу Cons расходов семьи, расположив расходы мужа, жены и любовницы в первый, второй и третий столбцы.  
В ответ запишите диагональные элементы (по побочной диагонали) этой матрицы через запятую (без пробела)

In [70]:
B = np.array([ Husband_Сonsumption , Wife_Сonsumption , Lover_Сonsumption ])
Cons = B.T

temp  = np.diagonal(Cons[:, ::-1])

task = '1.10.2'
print(f"Ответ к заданию {task}")
print(f"диагональные элементы (по побочной диагонали) матрицы Cons:= ", end="")
print(*temp, sep=",")

Ответ к заданию 1.10.2
диагональные элементы (по побочной диагонали) матрицы Cons:= 100,80,60


### Задание 1.10.3
Доходы представлены до уплаты налогов. Налоговая ставка — 13%. Вычислите матрицу доходов семьи Ивановых после уплаты налогов.  
В ответ запишите элементы из 1 строки этой матрицы через запятую (без пробелов)

In [71]:
Margin = 0.87*Inc

temp  = Margin[0]

task = '1.10.3'
print(f"Ответ к заданию {task}")
print(f"элементы из 1 строки этой матрицы доходов семьи Ивановых после уплаты налогов:= ", end="")
print(*temp, sep=",")

Ответ к заданию 1.10.3
элементы из 1 строки этой матрицы доходов семьи Ивановых после уплаты налогов:= 87.0,130.5,78.3


### Задание 1.10.4  
Вычислите матрицу P, которая покажет баланс семьи Ивановых за один месяц (то есть разницу между доходами и расходами).  
В ответ запишите элементы из 3 строки этой матрицы через запятую (без пробела)

In [72]:
P = Margin - Cons

temp = P[2]
task = '1.10.4'

print(f"Ответ к заданию {task}")
print(f"элементы из 3 строки матрицы баланса семьи Ивановых:= ", end="")
print(*temp, sep=",")

Ответ к заданию 1.10.4
элементы из 3 строки матрицы баланса семьи Ивановых:= 61.8,-26.900000000000006,-53.0


### 1.11. Умножение матриц
---
### Задание 1.11.1
1. Когда можно найти произведение двух матриц A • B?  

***Ответ:***
- $A = {1\ 2\ 1\choose 4 \ 4\ 4} , B = {1\ 0\ 6\choose 0 \ 1\ 0}$  
- А размера 8 на 3 и B размера 3 на 5

2. Для корректного умножения матриц должны совпадать:  

***Ответ:***
- Число столбцов левой матрицы и число строк правой верно

### Задание 1.11.2
В произведении C = AB матриц  
1. c~1~2  
2. с~3~4

In [85]:
np.dot(A,B)

array([[ 3,  4,  5,  7],
       [11,  8, 17,  0],
       [ 4,  3,  5,  0]])

In [86]:
A = np.array( [ [1,-1, 2, 4, 0] , [8, 2, 0, 5, 3] , [0, 1, 2, 1, 2] ] )
B = np.array( [ [1, 0, 1, 0] , [0, 0, 2, -1] , [1, 0, 1, 1], [0, 1, 1, 1], [1, 1, 0, -1] ] )
C = np.dot(A,B)
print(C)
temp1 = C[0,1]
temp2 = C[2,3]

task = '1.11.2'

print(f"Ответ к заданию {task}")
print(f"c 12:= {temp1}")
print(f"c 34:= {temp2}")

[[ 3  4  5  7]
 [11  8 17  0]
 [ 4  3  5  0]]
Ответ к заданию 1.11.2
c 12:= 4
c 34:= 0


### 1.12. Умножение на специальные матрицы
---
### Задание 1.12.2
Найдите АВ и ВА

In [87]:
A = np.array([[2, 0], [0, 3]])
B = np.array([[1, 1], [4, 5]])
print("AB")
print(np.dot(A,B))
print("BA")
print(np.dot(B,A))

AB
[[ 2  2]
 [12 15]]
BA
[[ 2  3]
 [ 8 15]]


### 1.13. Делители нуля
---
### 1.14. Умножение и транспонирование матриц
---
### Задание 1.14.2  
Найдите матрицу Грама G системы векторов:  
$a = {1\choose 1} , b = {2\choose -1}, c = {1\choose 2}$

In [88]:
X = np.array( [ [1,2,1] , [1,-1,2] ] )
task = '1.14.2'

print(f"Ответ к заданию {task}")
print(f"матрицу Грама G системы векторов")
print(np.dot(X.T,X))

Ответ к заданию 1.14.2
матрицу Грама G системы векторов
[[2 1 3]
 [1 5 0]
 [3 0 5]]


### 1.15. --> Практика. Умножение матриц
---
### Задача 1.15.1. 
Условие
```python 
A=np.array([[5, -1, 3, 1, 2],[-2, 8, 5, -1, 1]])
x=np.array([1, 2, 3, 4, 5])
```
Найдите произведение матрицы A и вектора x в том порядке, в котором их можно умножить.

In [90]:
A=np.array( [ [5,-1,3,1,2] , [-2,8,5,-1,1] ] )
x=np.array( [1,2,3,4,5] )
x1 = np.reshape(x,(5,1))

temp = np.dot(A,x1)

task = '1.15.1'
print(f"Ответ к заданию {task}")
print(f"произведение матрицы A и вектора x :=", end="")
print(*temp, sep=",")

Ответ к заданию 1.15.1
произведение матрицы A и вектора x :=[26],[30]


### Задание 1.15.2 
***Условие:*** Даны две матрицы:
```python
A = np.array([[1,9,8,5], [3,6,3,2], [3,3,3,3], [0,2,5,9], [4,4,1,2]])
B = np.array([[1,-1,0,1,1], [-2,0,2,-1,1]])
```
Найдите произведение матриц A и B в том порядке, в котором их можно умножить.
В ответ запишите элемент из 1 строки и 4 столбца

In [92]:
A=np.array([[1, 9, 8, 5], [3, 6, 3, 2], [3, 3, 3, 3], [0, 2, 5, 9], [4, 4, 1, 2]])
B=np.array([[1, -1, 0, 1, 1], [-2, 0, 2, -1, 1]])
C = np.dot(B,A)

temp= C[0,3]

task = '1.15.2'
print(f"Ответ к заданию {task}")
print(f"элемент из 1 строки и 4 столбца произведения матрицы A и B := {temp}")

Ответ к заданию 1.15.2
элемент из 1 строки и 4 столбца произведения матрицы A и B := 14


### Задание 1.15.3. 
***Условие:*** Дана система векторов:
```python
x = np.array([1,2,1,0,4])  
y = np.array([2,1,-1,1,0])  
z = np.array([-1,1,-1,0,0])  
```
Найдите матрицу Грама системы векторов x, y, z  
Введите все элементы этой матрицы через запятую (без пробела), перечисляя построчно:

In [94]:
x=np.array([1,2,1,0,4])
y=np.array([2,1,-1,1,0])
z=np.array([-1,1,-1,0,0])
A = np.array([x,y,z])

task = '1.15.3'

print(f"Ответ к заданию {task}")
print(f"матрица Грама G системы векторов:")
print(np.dot(A,A.T))

Ответ к заданию 1.15.3
матрица Грама G системы векторов:
[[22  3  0]
 [ 3  7  0]
 [ 0  0  3]]


### Задание 1.15.4. 
В салоне красоты «Феи ножниц» работает 8 стилистов: Аня, Борис, Вика, Галя, Дима, Егор, Женя и Юра.  
В dataframe Count_DF содержится информация по количеству услуг, оказанных каждым стилистом за апрель.  
В dataframe Price_DF содержится информация по стоимости услуг у каждого стилиста в тысячах рублей.  
Найдите вектор выручки Бориса

In [95]:
Count_DF = pd.DataFrame({'Женские стрижки': [10, 2, 12, 4, 6, 10, 22, 7], 
                                'Мужские стрижки': [5, 21, 12, 8, 25, 3, 1, 0], 
                                'Окрашивания':[12, 3, 0, 18, 27, 2, 4, 31],
                              'Укладка':[15, 25, 30, 14, 25, 17, 25, 31],
                                'Уход':[10, 6, 4, 5, 18, 12, 20, 28]
                                }, 
                               index=['Аня', 'Борис', 'Вика', 'Галя', 'Дима', 'Егор', 'Женя','Юра'])
Price_DF = pd.DataFrame({'Женские стрижки': [2, 1.8, 2, 1.8, 2.5, 5, 1.1, 4.5], 
                                'Мужские стрижки': [1.5, 2.5, 2, 1.2, 3.5, 5, 1, 4], 
                                'Окрашивания':[1, 1, 0, 2.8, 2, 3, 1.5, 2.5],
                              'Укладка':[0.8, 1, 0.5, 0.8, 1, 2, 0.5, 1],
                                'Уход':[1, 1, 2, 2, 1.5, 2.5, 1.7, 2] 
                                }, 
                               index=['Аня', 'Борис', 'Вика', 'Галя', 'Дима', 'Егор', 'Женя','Юра'])

In [99]:
C = Count_DF.values
P = Price_DF.values

temp = C[1]*P[1]

task = '1.15.4'
print(f"Ответ к заданию {task}")
print(f"вектор выручки Бориса :=", end="")
print(*temp, sep=",")

Ответ к заданию 1.15.4
вектор выручки Бориса :=3.6,52.5,3.0,25.0,6.0


### Задание 1.15.5. 
Найдите вектор прибыли салона по стилистам.  
Если за каждую услугу стилисты платят определенную комиссию салону.  
Вектор комиссий com=\[0.2, 0.2, 0.3, 0.1, 0.1\]  
Введите координаты вектора через запятую (без пробела):

In [110]:
com = np.array([0.2, 0.2, 0.3, 0.1, 0.1])

temp = C*P@com

task = '1.15.5'
print(f"Ответ к заданию {task}")
print(f"вектор прибыли салона по стилистам :=", end="")
print(*temp, sep=",")

Ответ к заданию 1.15.5
вектор прибыли салона по стилистам :=11.3,15.22,11.900000000000002,20.6,41.900000000000006,21.200000000000003,11.49,38.25


### Задание 1.15.6. 
Найдите вектор прибыли стилистов

In [112]:
com_stylist = np.ones(5)-com

temp = R@com_stylist

task = '1.15.6'
print(f"Ответ к заданию {task}")
print(f"вектор прибыли стилистов :=", end="")
print(*temp, sep=",")

Ответ к заданию 1.15.6
вектор прибыли стилистов :=50.2,74.88000000000001,59.10000000000001,67.8,166.60000000000002,113.80000000000001,66.21000000000001,157.75


### 1.16. Обратная матрица

In [126]:
A = np.array([[1,0],[0,1]])
print("матрица А")
print(A)
print("матрица обратная к А")
print(np.linalg.inv(A))
print("---")

C = np.array([[2,0],[0,5]])
print("матрица C")
print(C)
print("матрица обратная к C")
print(np.linalg.inv(C))

матрица А
[[1 0]
 [0 1]]
матрица обратная к А
[[1. 0.]
 [0. 1.]]
---
матрица C
[[2 0]
 [0 5]]
матрица обратная к C
[[0.5 0. ]
 [0.  0.2]]


### Задание 1.16.1

In [121]:
D = np.array([[1,2],[2,4]])
print("матрица D")
print(D)

task = '1.16.1'
print(f"Ответ к заданию {task}")
print("матрица обратная не существует")

матрица D
[[1 2]
 [2 4]]
Ответ к заданию 1.16.1
матрица обратная не существует


### Задания 1.16.3 - 1.16.4

In [125]:
B = np.array([[1,2],[2,5]])
print("матрица В")
print(B)

task = '1.16.3'
print(f"Ответ к заданию {task}")
print("матрица обратная к B")
print(np.linalg.inv(B))

матрица В
[[1 2]
 [2 5]]
Ответ к заданию 1.16.3
матрица обратная к B
[[ 5. -2.]
 [-2.  1.]]


### 1.17. Определитель матрицы

In [123]:
print (f"детерминант матрицы A := {np.linalg.det(A)}")
print (f"детерминант матрицы B := {np.linalg.det(B)}")
print (f"детерминант матрицы C := {np.linalg.det(C)}")
print (f"детерминант матрицы D := {np.linalg.det(D)}")

детерминант матрицы A := 1.0
детерминант матрицы B := 1.0
детерминант матрицы C := 9.999999999999998
детерминант матрицы D := 0.0


### Задание 1.17.1
Найдите det(A), det(B), det(A+B), если
```python
A = np.array([[1,2],[1,1]])
B = np.array([[5,-2],[-1,4]])
```

In [128]:
A = np.array([[1,2],[1,1]])
B = np.array([[5,-2],[-1,4]])

temp = np.linalg.det(A)
temp2 = np.linalg.det(B)
temp3 = np.linalg.det(A+B)

task = '1.17.1'
print(f"Ответ к заданию {task}")
print(f"det(A) := {temp}")
print(f"det(B) := {temp2}")
print(f"det(A+B) := {temp3}")

Ответ к заданию 1.17.1
det(A) := -1.0
det(B) := 17.999999999999996
det(A+B) := 29.99999999999999


### 1.18. Линейная (не)зависимость ч.1
---
### 1.19. Линейная (не)зависимость ч.2
---
### 1.20. --> Практика. Обратная матрица, ранг, определитель

In [131]:
# обратная матрица - все ок
A1=np.array([[1,2,3],[4,5,6],[7,8,10]])
print('A1:\n',A1)

A1:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8 10]]


In [132]:
print('rk(A3):\n',np.linalg.matrix_rank(A1))

rk(A3):
 3


In [133]:
# обратная матрица - все ок
A1_inv=np.linalg.inv(A1)
print('A1 inversed:\n',A1_inv)

A1 inversed:
 [[-0.66666667 -1.33333333  1.        ]
 [-0.66666667  3.66666667 -2.        ]
 [ 1.         -2.          1.        ]]


In [134]:
# обратная матрица - все ок
print('A1 @ A1 inversed=E check:\n',A1@A1_inv,1)
print(np.round(A1@A1_inv,1))
print('check OK')

A1 @ A1 inversed=E check:
 [[ 1.00000000e+00  8.88178420e-16 -4.44089210e-16]
 [ 0.00000000e+00  1.00000000e+00 -1.77635684e-15]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00]] 1
[[ 1.  0. -0.]
 [ 0.  1. -0.]
 [ 0.  0.  1.]]
check OK


In [135]:
# обратная матрица - вырожденный случай
A2=np.array([[1,2,3],[4,5,6],[1,2,3]])
print('A2:\n',A2)

A2:
 [[1 2 3]
 [4 5 6]
 [1 2 3]]


In [136]:
# обратная матрица - вырожденный случай
print('rk(A3):\n',np.linalg.matrix_rank(A2))

rk(A3):
 2


In [137]:
# обратная матрица - вырожденный случай
np.linalg.inv(A2)

LinAlgError: Singular matrix

In [138]:
# обратная матрица - magic
A3=np.array([[1,2,3],[4,5,6],[7,8,9]])
print('A3:\n',A3)

A3:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [139]:
# обратная матрица - magic
print('rk(A3):\n',np.linalg.matrix_rank(A3))

rk(A3):
 2


In [140]:
# обратная матрица - magic
print('A3 inversed:\n',np.linalg.inv(A3))

A3 inversed:
 [[-4.50359963e+15  9.00719925e+15 -4.50359963e+15]
 [ 9.00719925e+15 -1.80143985e+16  9.00719925e+15]
 [-4.50359963e+15  9.00719925e+15 -4.50359963e+15]]


In [141]:
# обратная матрица - magic
print('A3 @ A3 inversed = E check:\n',A3@np.linalg.inv(A3))
print('check failed')

A3 @ A3 inversed = E check:
 [[ 0.  0.  0.]
 [-4.  0. -4.]
 [ 0.  0.  0.]]
check failed


In [142]:
print('det(A1)):\n',np.linalg.det(A1))

print('det(A2)):\n',np.linalg.det(A2))

print('det(A3)):\n',np.linalg.det(A3))

det(A1)):
 -2.9999999999999982
det(A2)):
 0.0
det(A3)):
 6.66133814775094e-16


In [143]:
# обратная матрица - нестойчивость
A4=np.array([[1,2,3],[4,5,6],[1,2,3.00005]])
print('A4:\n',A4)
print('rk(A4):\n',np.linalg.matrix_rank(A4))
print('det(A4):\n',np.linalg.det(A4))
print('A4 inverse:\n',np.linalg.inv(A4))

A4:
 [[1.      2.      3.     ]
 [4.      5.      6.     ]
 [1.      2.      3.00005]]
rk(A4):
 3
det(A4):
 -0.00014999999999965044
A4 inverse:
 [[-2.00016667e+04  6.66666667e-01  2.00000000e+04]
 [ 4.00013333e+04 -3.33333333e-01 -4.00000000e+04]
 [-2.00000000e+04  0.00000000e+00  2.00000000e+04]]


In [144]:
# обратная матрица - нестойчивость вблизи нулевого определителя
A5=np.array([[1,2,3],[4,5,6],[1,2,3.00000005]])
print('A5:\n',A5)
print('rk(A5):\n',np.linalg.matrix_rank(A5))
print('det(A5):\n',np.linalg.det(A5))
print('A5 inverse:\n',np.linalg.inv(A5))

A5:
 [[1.         2.         3.        ]
 [4.         5.         6.        ]
 [1.         2.         3.00000005]]
rk(A5):
 3
det(A5):
 -1.5000000042064706e-07
A5 inverse:
 [[-2.00000016e+07  6.66666667e-01  1.99999999e+07]
 [ 4.00000012e+07 -3.33333333e-01 -3.99999999e+07]
 [-1.99999999e+07  0.00000000e+00  1.99999999e+07]]


In [145]:
# обратимость матрицы Грама линейно независимой системы векторов
v1=np.array([1,2,1])
v2=np.array([1,1,1])
A=np.array([v1,v2]).T

In [146]:
print('A:\n',A)
print('Матрица Грама:\n',A.T@A)

print('Ранг матрицы Грама:\n',np.linalg.matrix_rank(A.T@A))

print('Определитель матрицы Грама:\n',np.linalg.det(A.T@A))

print('Обратная к матрице Грама:\n',np.linalg.inv(A.T@A))

A:
 [[1 1]
 [2 1]
 [1 1]]
Матрица Грама:
 [[6 4]
 [4 3]]
Ранг матрицы Грама:
 2
Определитель матрицы Грама:
 2.0000000000000004
Обратная к матрице Грама:
 [[ 1.5 -2. ]
 [-2.   3. ]]


### Задание 1.20.1. 
Найдите обратную матрицу к матрице А  
В ответ запишите элемент из 2 строки и 1 столбца

In [149]:
A=np.array( [[ 8 , 6 ,11],[ 7 , 5 , 9],[ 6 ,10,  6]])

temp = np.linalg.inv(A)[1,0]

task = '1.20.1'
print(f"Ответ к заданию {task}")
print(f"элемент из 2 строки и 1 столбца обратной матрицы к матрице А := ", end="")
print(temp, sep=",")

Ответ к заданию 1.20.1
элемент из 2 строки и 1 столбца обратной матрицы к матрице А := 0.375


Задание 1.20.1 элемент из 2 строки и 1 столбца обратной матрицы к матрице А :=0.375

### Задание 1.20.2. 
Найдите ранг системы векторов v1, v2, v3, v4

In [152]:
v1=np.array([ 9, 10,  7,  7,  9])
v2=np.array([2, 0, 5, 1, 4])
v3=np.array([4, 0, 0, 4, 1])
v4=np.array([ 3, -4,  3, -1, -4])

B = np.array([v1,v2,v3,v4])

temp = np.linalg.matrix_rank(B)

task = '1.20.2'
print(f"Ответ к заданию {task}")
print(f"ранг системы векторов v1, v2, v3, v4 := ", end="")
print(temp, sep=",")

Ответ к заданию 1.20.2
ранг системы векторов v1, v2, v3, v4 := 4


### Задание 1.20.4. 
Найдите матрицу Грама системы векторов v1, v2, v3, v4  
В ответ запишите элемент из 1 строки и 4 столбца

In [153]:
X = B.T
G = X.T @ X

temp = G[0,3]

task = '1.20.4'
print(f"Ответ к заданию {task}")
print(f"элемент из 1 строки и 4 столбца матрицы Грама системы векторов v1, v2, v3, v4 := ", end="")
print(temp, sep=",")

Ответ к заданию 1.20.4
элемент из 1 строки и 4 столбца матрицы Грама системы векторов v1, v2, v3, v4 := -35


### Задание. 1.20.5. 
Найдите определитель матрицы Грама системы v1, v2, v3, v4  
***Ответ округлите до целой части:***

In [156]:
temp = np.linalg.det(G)

task = '1.20.5'
print(f"Ответ к заданию {task}")
print(f"определитель матрицы Грама системы v1, v2, v3, v4 := ", end="")
print(round(temp,0), sep=",")

Ответ к заданию 1.20.5
определитель матрицы Грама системы v1, v2, v3, v4 := 3716648.0


### Задание 1.20.7. 
Найдите обратную матрицу к матрице Грама системы v1, v2, v3, v4  
В ответ запишите элемент из 3 строки и 1 столбца, округлив его до трёх знаков после запятой

In [158]:
temp = np.linalg.inv(G)[2,0]

task = '1.20.7'
print(f"Ответ к заданию {task}")
print(f"элемент из 3 строки и 1 столбца обратной матрицы к матрице Грама системы v1, v2, v3, v4   := ", end="")
print(round(temp,3), sep=",")

Ответ к заданию 1.20.7
элемент из 3 строки и 1 столбца обратной матрицы к матрице Грама системы v1, v2, v3, v4   := -0.026


конец модуля